### ISSUE TITLE
Crashing JEI & the BlastingRecipe typecast exception

### ISSUE THREAD

**Issue by alaestor** [kimcodekill/BetterVanilla#1]
Game version 1.14.4
Forge Version 28.1.26

BV 1.0.2 has a bug which generates a conflict with JEI 6.0.0.13 causing JEI to not appear in game.

I believe the culprit is likely this typecast error raised upon loading / worldgen

> [Client thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: chokemonster.bettervanilla.recipes.BlastingRecipe cannot be cast to net.minecraft.item.crafting.BlastingRecipe

which causes

> [Client thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
> 
> java.lang.ClassCastException: chokemonster.bettervanilla.recipes.BlastingRecipe cannot be cast to net.minecraft.item.crafting.BlastingRecipe
> 
> 	at mezz.jei.plugins.vanilla.crafting.VanillaRecipeValidator.getValidRecipes(VanillaRecipeValidator.java:88) ~[?:6.0.0.13]
> 
> 	at mezz.jei.plugins.vanilla.VanillaPlugin.registerRecipes(VanillaPlugin.java:181) ~[?:6.0.0.13]

which I believe is causing JEI to fail to initialize properly. [Attached logs](https://github.com/kimcodekill/BetterVanilla/files/3668026/BV.crashing.JEI.typecast.except.zip)

There is likely a way for JEI to handle this gracefully, but since it's caused by your mod misbehaving I believe it to be appropriate that I report it to you instead (symptom v. cause). Whether or not any of the other mods I currently have loaded play into this is unknown as I haven't bothered to test in an isolated environment; regardless, this typecast error should be fixed. I'm not familiar with Java but I'd imagine there to be some operator or method define which should be able to solve the type conversion (either that or resort to inheritance)

**Comment by kimcodekill** [comment]
I know what's wrong here, JEI is looking for the vanilla "Blasting Recipe" json shape and can't find it when BetterVanilla replaces it. I'm kind of busy with uni at the moment but the fix is probably arbitrary. I'll look at it as soon as possible.

**Comment by Thelnfamous1** [comment]
Very easy to fix, I did it by using a single interface class [you wrote](https://github.com/kimcodekill/BetterVanilla/blob/e84a1201ec01ae7e79d5152d1e514dac400884bb/src/main/java/chokemonster/bettervanilla/interfaces/IBetterRecipeType.java) and replacing any usage of IRecipeType.BLASTING with that custom IRecipeType. Although now you would need to make new JSON recipe files for everything the vanilla blast furnace could smelt, and also recreate the Blast Furnace GUI so it allows shift-clicking items into the ingredient slot.
